[workspace]
resolver = "2"
members = [
  ".",
  "members/libpt-core",
  "members/libpt-bintols",
  "members/libpt-math",
  "members/libpt-bin",
  "members/libpt-log",
  "members/libpt-net",
  "members/libpt-hedu",
]
default-members = [".", "members/libpt-bin", "members/libpt-core"]
[workspace.package]
publish = true
version = "0.2.9"
edition = "2021"
authors = ["Christoph J. Scherr <software@cscherr.de>"]
license = "MIT"
description = "Personal multitool"
readme = "README.md"
homepage = "https://git.cscherr.de/PlexSheep/libpt"
repository = "https://git.cscherr.de/PlexSheep/libpt"
keywords = ["cli", "library"]
categories = [
  "command-line-utilities",
  "development-tools",
  "development-tools::ffi",
]

[workspace.dependencies]
anyhow = "1.0.79"
thiserror = "1.0.56"
libpt-log = { path = "../libpt-log" }
libpt-bintols = { path = "../libpt-bintols" }

[package]
name = "libpt"
publish.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[features]
default = ["log", "core"]
all = ["default", "math", "log", "bintols", "net", "ccc", "hedu", "core"]
core = []
fw = []
math = []
log = []
bintols = []
net = []
ccc = ["math"]
hedu = ["bintols"]

[lib]
name = "libpt"
crate-type = [
  "dylib",     # .dll, .so, .dynlib
  "staticlib", # .lib, .a
  "rlib",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpt-bintols = { version = "0.2.9", path = "members/libpt-bintols" }
libpt-core = { version = "0.2.9", path = "members/libpt-core" }
libpt-hedu = { version = "0.2.9", path = "members/libpt-hedu" }
libpt-log = { version = "0.2.9", path = "members/libpt-log" }
libpt-math = { version = "0.2.9", path = "members/libpt-math" }
libpt-ccc = { version = "0.2.9", path = "members/libpt-ccc" }
libpt-net = { version = "0.2.9", path = "members/libpt-net" }
