name: Cargo Check, Format, Fix, Test and publish
on:
  push:
    branches:
      - master

jobs:
  format:
    name: cargo CD
    steps:
      - run: |
          echo Registry Token: ${{ secrets.CARGO_PUBLISH_CSCHERR }}
      - name: get repo
        uses: actions/checkout@v4
      - name: install rust
        uses: dtolnay/rust-toolchain@stable
      - name: config custom registry
        run: |
          mkdir -p ~/.cargo/
          echo -e '[registry]
          cscherr= "cscherr"

          [registries.cscherr]
          index = "sparse+https://git.cscherr.de/api/packages/PlexSheep/cargo/"
          token = "${{ secrets.CARGO_PUBLISH_CSCHERR }}"
          ' > ~/.cargo/config.toml
          cat ~/.cargo/config.toml
          echo Registry Token: ${{ secrets.CARGO_PUBLISH_CSCHERR }}
      - name: install cargo workspace
        run: cargo install cargo-workspaces
      - name: publish crates on git.cscherr.de
        run: |
            cargo workspaces publish --registry cscherr skip
