[package]
name = "libpt-py"
version = "0.3.11"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "libpt"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.19.0", features = ["full", "extension-module"] }
